from fuzzywuzzy import fuzz

GREETINGS = [
    "hi",
    "hi bot",
    "hi hayya bot",
    "good",
    "good morning!",
    "good afternoon!",
    "good evening!",
    "hello",
    "hey there",
    "hi there!",
    "hey!",
    "greetings!",
    "howdy!",
    "salutations!",
    "welcome!",
    "nice to see you!",
    "it's a pleasure to meet you!",
    "how are you doing?",
    "how's it going?",
    "how's your day been?",
    "what's up?",
    "how have you been?",
    "long time no see!",
    "what's new?",
    "how's everything in your world?",
    "good day!",
    "hola!",
    "bonjour!",
    "ciao!",
    "how are you?",
    "what's happening?",
    "hey, how's everything?",
    "hey, what's going on?",
    "hey, how have you been?",
    "how's life treating you?",
    "what's the latest?",
    "how's your week been so far?",
    "hey, how's the weather today?",
    "hi, how's your day shaping up?",
    "hey, how's your weekend going?",
    "how's everything going with you?",
    "bye",
    "byee",
    "take care!",
    "until next time!",
    "see you later!",
    "goodbye!",
    "farewell!",
    "catch you later!",
    "have a great day!",
    "stay well!",
    "talk to you soon!",
    "keep in touch!",
    "wishing you the best!",
    "adios!",
    "bye for now!",
    "see you around!",
    "it was nice chatting with you!",
    "take it easy!",
    "enjoy the rest of your day!",
    "see you soon!",
    "until we meet again!",
    "stay safe!",
    "as-salamu alaykum",
    "marhaban",
    "sabah al khayr",
    "masa al khayr",
    "shukran",
    "marhaba",
    "shukaran",
    "sabah al-khayr",
    "masa al-khayr",
    "hiya!",
    "how's your day?",
    "rise and shine!",
    "g'day mate!",
    "shalom!",
    "namaste!",
    "hi there, sunshine!",
    "yo!",
    "how goes it?",
    "howdy-do!",
    "hey sunshine!",
    "hey, stranger!",
    "till we meet again!",
    "stay fabulous!",
    "until next rendezvous!",
    "toodles!",
    "farewell, amigo!",
    "to infinity and beyond!",
    "keep on shining!",
    "until our paths cross again!",
    "until the next sunrise!",
    "be well and prosper!",
    "until the next moonrise!",
    "may your days be merry and bright!",
    "keep the vibe alive!",
    "keep the spirit high!",
    "thank you, goodbye",
    "thank you, bye",
    "see ya!",
    "bye-bye!",
    "take care!",
    "so long!",
    "farewell!",
    "bye now!",
    "until later!",
    "bye for now!",
    "catch you later!",
    "goodbye then!",
    "see you soon!",
    "bye!",
    "take it easy!",
    "later!",
    "peace out!",
    "adios!",
    "have a good one!",
    "bye for now!",
    "till next time!",
    "bye-bye for now!",
    "until we meet again!",
    "goodbye!",
    "see you around!",
    "take care of yourself!",
    "bye, friend!",
    "until next time!",
    "have a great day!",
    "farewell for now!",
    "bye, take care!",
    "until we chat again!",
    "so long, friend!",
    "bye, see you soon!",
    "stay well!",
    "goodbye, my friend!",
    "until next time, take care!",
    "bye, until later!"
]


def is_greeting(question):
    question = question.lower()
    for temp in GREETINGS:
        if fuzz.ratio(question,temp)>70:
            return 1

    return 0
